"use strict";

exports.HORIZONTAL_GROUP_ORIENTATION = exports.APPOINTMENT_SETTINGS_KEY = exports.LIST_ITEM_CLASS = exports.LIST_ITEM_DATA_KEY = void 0;
var LIST_ITEM_DATA_KEY = 'dxListItemData';
exports.LIST_ITEM_DATA_KEY = LIST_ITEM_DATA_KEY;
var LIST_ITEM_CLASS = 'dx-list-item';
exports.LIST_ITEM_CLASS = LIST_ITEM_CLASS;
var APPOINTMENT_SETTINGS_KEY = 'dxAppointmentSettings';
exports.APPOINTMENT_SETTINGS_KEY = APPOINTMENT_SETTINGS_KEY;
var HORIZONTAL_GROUP_ORIENTATION = 'horizontal';
exports.HORIZONTAL_GROUP_ORIENTATION = HORIZONTAL_GROUP_ORIENTATION;