name: Preview

on:
  pull_request:
    types: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
            playground:
              - 'playground/sample.html'

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.changed.outputs.playground == 'true'
        with:
          message: |
            Preview is building

      - name: Build
        if: steps.changed.outputs.playground == 'true'
        run: |
          npm i
          npm run build
          mv playground ..
        env:
          PR: ${{ github.event.number }}

      - name: Checkout to pages
        run: |
          git fetch --depth=1
          git checkout gh-pages
          rm -rf $PR
          mkdir $PR
          mv artifacts $PR
          mv ../playground $PR
        env:
          PR: ${{ github.event.number }}

      - name: Commit to pages
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.changed.outputs.playground == 'true'
        with:
          file_pattern: ${{ github.event.number }}
          branch: gh-pages
          commit_message: build

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.changed.outputs.playground == 'true'
        with:
          message: |
            Preview: https://pomahtri.github.io/DevExtreme-preview/${{ github.event.number }}/playground/sample.html

      - name: Delete playground
        if: steps.changed.outputs.playground == 'true'
        run: |
          git checkout ${{ github.head_ref }}
          rm playground/sample.html

      - name: Commit deleted playground
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.changed.outputs.playground == 'true'
        with:
          commit_message: Automated Change
          file_pattern: playground/sample.html
